version: '3'
services:
  dashboard:
      build: .
      stop_signal: SIGINT
      ports:
        - "4000:80"
      volumes:
        - ./app:/app
      depends_on:
      - database
  database: 
    image: nkhanhle23-earnings-sql-server:latest
    restart: always 
    environment:
      - MYSQL_ROOT_PASSWORD=''
      - MYSQL_DATABASE='earnings'
      - DOLT_REMOTE_ORIGIN='nkhanhle23/earnings'
    ports:
    - "3306:3306"
    volumes:
    - ./database:/var/lib/mysql

    
